def main():
    print("BIENVENIDO A LA CALCULADORA DE PRESUPUESTOS")
    print("1- Presupuesto de Ventas")
    print("2- Presupuesto de saldo de clientes y flujo de efectivo")
    print("3- Presupuesto de produccion")
    print("4- Presupuesto de requerimiento de Materia prima")
    print("5- Presupuesto de Compra de materiales")
    print("6- Presupuesto determinacion de saldo proveedores y flujo de salidas")
    print("7- Presupuesto de mano de obra directa")
    print("8- Presupuesto de GIF ")
    print("9- Presupuesto de gastos de operacion")
    print("10-Presupuesto determinacion del costo unitario de productos terminados")
    print("11-Presupuesto de valuacion de inventarios finales")
    print("12-Estado de costo de producción y ventas")
    print("13-Estado de resultados")
    print("14-Estado de flujo de efectivo")
    print("15-Balance General")
    print("16-Finalizar el programa")
    
def Numero1():
    print("***Presupuesto de ventas***")
    print("Producto A")
    print("Semestre 1")
    unidades_1A= int(input("Ingrese unidades a vender Semestre 1: "))
    precio_de_venta1A = int(input("Ingrese precio de venta del Semestre 1: "))
    importe_ventas1A = (unidades_1A * precio_de_venta1A )
    print(f"Ventas esperadas del Semestre 1 del producto A es {importe_ventas1A}")
    print("Semestre 2")
    unidades_2A = int(input("Ingrese unidades a vender del Semestre 2: "))
    precio_de_venta2A = int(input("Ingrese precio de venta del Semestre 2: "))
    importe_ventas2A = ( unidades_2A * precio_de_venta2A )
    print(f"Ventas esperadas del Semestre 2 del Producto A: {importe_ventas2A}")
    print(f"Ventas esperadas total del 2020: {importe_ventas1A + importe_ventas2A }")
    print("\n")
    
    print("Producto BI")
    print("Semestre 1")
    unidades_1BI = int(input("Ingrese unidades a vender Semestre 1: "))
    precio_venta1BI = int(input("Ingrese precio de venta Semestre 1: "))
    importe_venta1BI = ( unidades_1BI * precio_venta1BI)
    print(f"Ventas esperadas del Semestre 1 del Producto BI: {importe_venta1BI}")
    print("Semestre 2")
    unidades_2B1 = int(input("Unidades a vender Semestre 2: "))
    precio_venta2B1 = int(input("Precio de venta Semestre 2: "))
    importe_venta2BI = ( unidades_2B1 * precio_venta2B1)
    print(f"Ventas esperadas del Semestre 2 del Producto BI: {importe_venta2BI}")
    print(f"Ventas esperadas total del 2020: {importe_venta1BI + importe_venta2BI}")
    print("\n")
    
    print("Producto FA")
    print("Semestre 1")
    unidades_1FA = int(input("Ingrese unidades a vender Semestre 1: "))
    precio_venta1FA = int(input("Ingrese precio de venta Semestre 1: "))
    importe_venta1FA = (unidades_1FA * precio_venta1FA)
    print(f"Ventas esperadas del Semestre 1 del Producto FA: {importe_venta1FA}")
    print("Semestre 2")
    unidades_2FA = int(input("Unidades a vender Semestre 2: "))
    precio_venta2FA = int(input("Precio de venta Semestre 2: "))
    importe_venta2FA = (unidades_2FA * precio_venta2FA)
    print(f"Ventas esperadas del Semestre 2 del Producto FA: {importe_venta2FA}")
    print(f"Ventas esperadas total del 2020: {importe_venta1FA + importe_venta2FA}")
    print("\n")
    
    total_venta1 = (importe_ventas1A+importe_venta1BI+importe_venta1FA)
    total_venta2 = (importe_ventas2A+importe_venta2BI+importe_venta2FA)
    print(f"La suma de ventas Semestre 1 es: {total_venta1}")
    print(f"La suma de ventas Semestre 2 es: {total_venta2}")
    print(f"El total de ventas por cada Semestre es de {total_venta1 + total_venta2}")
    
def Numero2():
    print("***Determinacion de saldo de clientes y flujo de efectivo***")
    saldo_clientes2018 = int(input("Escriba el saldo de la cuenta clientes del 31 de Diciembre del 2018: "))
    ventas_2021 = int(input("Escriba las ventas del año 2021: "))
    total_clte2021 = (saldo_clientes2018 + ventas_2021)
    print(f"El total de ventas 2021 es {total_clte2021}")
    print("Entradas de efectivo:")
    print(f"Cobranza del 2018 es {saldo_clientes2018}")
    print(f"Cobranza del 2021 es {ventas_2021 * 0.8}")
    entradas_2021 = (ventas_2021  + saldo_clientes2018)
    print(f"Total cobranza 2021: {entradas_2021}")
    print(f"Saldo Clientes 2021: { total_clte2021 - entradas_2021}")
    
    
def Numero3():
    print("**Presupuesto de produccion***")
    print("Producto A")
    print("Semestre 1")
    uav1CL = int(input("Unidades a vender del Semestre 1: "))
    invt_final1CL = int(input("Inventario final del Semestre 1: "))
    total_unidades1CL = (uav1CL + invt_final1CL)
    print(f"Total de unidades del Semestre 1: {total_unidades1CL}")
    print(f"Inventario inicial del Semestre 1: {invt_final1CL}")
    unidades_prodCL1 = (total_unidades1CL - invt_final1CL)
    print(f"* Unidades a producir son del Semestre 1: {unidades_prodCL1}")
    print("\n")

    print("-Semestre 2")
    uav2CL = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CL = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CL = (uav2CL + invt_final2CL)
    print(f"Total de unidades del Semestre 2: {total_unidades2CL}")
    print(f"Inventario inicial del Semestre 2: {invt_final1CL}")
    unidades_prodCL2 = (total_unidades2CL - invt_final1CL)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCL2}")
    print("\n")

    print("Total 2018")
    total_uds_fin = (uav1CL + uav2CL)
    print(f"* Unidades a vender en total: {total_uds_fin}")
    print(f"* Inventario final total: {invt_final2CL}")
    total_unidades = (total_uds_fin + invt_final2CL)
    print(f"Total de unidades: {total_unidades} ")
    print(f"* Inventario inicial del total es {invt_final1CL}")
    print(f"** Unidades a producir totales: {total_unidades - invt_final1CL}")
    print("\n")

    print("Producto BI")
    print("Semestre 1")
    uavCE1 = int(input("Ingrese las unidades a vender del 1er Semestre: "))
    invt_final1CE = int(input("Ingrese el inventario final del Semestre 1: "))
    total_unidades1CE = (uavCE1 + invt_final1CE)
    print(f"* Total de unidades del Semestre 1: {total_unidades1CE}")
    print(f"* Inventario inicial del Semestre 1: {invt_final1CE}")
    unidades_prodCE1 = (total_unidades1CE - invt_final1CE)
    print(f"* Unidades a producir del Semestre 1: {unidades_prodCE1}")
    print("\n")

    print("Semestre 2")
    uni_a_venderCE2 = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CE = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CE = (uni_a_venderCE2 + invt_final2CE)
    print(f"* Total de unidades del Semestre 2: {total_unidades2CE}")
    print(f"* Inventario inicial del Semestre 2: {invt_final1CE}")
    unidades_prodCE2 = (total_unidades2CE - invt_final1CE)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCE2}")
    print("\n")

    print("Total 2018")
    total_uds_finCE = (uavCE1 + uni_a_venderCE2)
    print(f"* Unidades a vender en total: {total_uds_finCE}")
    print(f"* Inventario final total: {invt_final2CE}")
    total_UnidadesCE = (total_uds_finCE + invt_final2CE)
    print(f"* Total de unidades: {total_UnidadesCE} ")
    print(f"* Inventario inicial del total: {invt_final1CE}")
    print(f"** Unidades a producir totales: {total_UnidadesCE - invt_final1CE}")
    print("\n")

    print("Producto FA")
    print("-Semestre 1")
    uavCR1 = int(input("Ingrese las unidades a vender del Semestre 1: "))
    invt_final1CR = int(input("Ingrese el inventario final del Semestre 1: "))
    total_unidades1CR = (uavCR1 + invt_final1CR)
    print(f"Total de unidades del Semestre 1: {total_unidades1CR}")
    print(f"Inventario inicial del Semestre 1: {invt_final1CR}")
    unidades_prodCR1 = (total_unidades1CR - invt_final1CR)
    print(f"Unidades a producir del Semestre 1: {unidades_prodCR1}")
    print("\n")

    print("Semestre 2")
    uavCR2 = int(input("Ingrese las unidades a vender del Semestre 2: "))
    invt_final2CR = int(input("Ingrese el inventario final del Semestre 2: "))
    total_unidades2CR = (uavCR2 + invt_final2CR)
    print(f"* Total de unidades del Semestre 2: {total_unidades2CR}")
    print(f"* Inventario inicial del Semestre 2: {invt_final1CR}")
    unidades_prodCR = (total_unidades2CR - invt_final1CR)
    print(f"* Unidades a producir son del Semestre 2: {unidades_prodCR}")
    print("\n")

    print("Total 2018")
    total_uds_finCR = (uavCR1 + uavCR2)
    print(f"* Unidades a vender en total: {total_uds_finCR}")
    print(f"* Inventario final total: {invt_final2CR}")
    total_UnidadesCR = (total_uds_finCR + invt_final2CR)
    print(f"* Total de unidades: {total_UnidadesCR} ")
    print(f"* Inventario inicial del total: {invt_final1CR}")
    print(f"** Unidades a producir totales: {total_UnidadesCR - invt_final1CR}")
    print("\n")
    
def Numero4():
    print("***Presupuesto de requerimiento de materia prima***")
    print("Producto A")
    print("Semestre 1")
    unidades_a_prodCL1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("Material A")
    requerimiento_materialA = float(input("Ingrese el requerimiento de material A: "))
    materialACL1 = (unidades_a_prodCL1 * requerimiento_materialA)
    print(f"* Total de Material A requerido: {materialACL1}")
    print("Material B")
    requerimiento_materialB = float(input("Ingrese el requerimiento de material B: "))
    materialBCL1 = (unidades_a_prodCL1 * requerimiento_materialB)
    print(f"* Total de Material B requerido: {materialBCL1}")
    print("Material C")
    requerimiento_materialC = float(input("Ingrese el requerimiento de material C: "))
    materialCCL1 = (unidades_a_prodCL1 * requerimiento_materialC)
    print(f"* Total de Material C requerido: {materialCCL1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCL2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("Material A")
    requerimiento_materialA2 = float(input("Ingrese el requerimiento de material A: "))
    materialACL2 = (unidades_a_prodCL2 * requerimiento_materialA2)
    print(f"* Total de Material A requerido: {materialACL2}")
    print("Material B")
    requerimiento_materialB2 = float(input("Ingrese el requerimiento de material B: "))
    materialBCL2 = (unidades_a_prodCL2 * requerimiento_materialB2)
    print(f"* Total de Material B requerido: {materialBCL2}")
    print("Material C")
    requerimiento_materialC2 = float(input("Ingrese el requerimiento de material C: "))
    materialCCL2 = (unidades_a_prodCL2 * requerimiento_materialC2)
    print(f"* Total de Material C requerido: {materialCCL2}")
    print("\n")

    print("Total 2018")
    unidades_a_prodCLT = int(input("> Suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialAT = float(input("Ingrese el requerimiento de material A: "))
    materialACLT = (unidades_a_prodCLT * requerimiento_materialAT)
    print(f"* Total de Material A requerido: {materialACLT}")
    print("-Material B")
    requerimiento_materialBT = float(input("Ingrese el requerimiento de material B: "))
    materialBCLT = (unidades_a_prodCLT * requerimiento_materialBT)
    print(f"* Total de Material B requerido: {materialBCLT}")
    print("-Material C")
    requerimiento_materialCT = float(input("Ingrese el requerimiento de material C: "))
    materialCCLT = (unidades_a_prodCLT * requerimiento_materialCT)
    print(f"* Total de Material C requerido: {materialCCLT}")
    print("\n")

    print("Producto BI")
    print("Semestre 1")
    unidades_a_prodCE1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("-Material A")
    requerimiento_materialACE = float(input("Ingrese el requerimiento de material A: "))
    materialACE1 = (unidades_a_prodCE1 * requerimiento_materialACE)
    print(f"* Total de Material A requerido: {materialACE1}")
    print("-Material B")
    requerimiento_materialBCE = float(input("Ingrese el requerimiento de material B: "))
    materialBCE1 = (unidades_a_prodCE1 * requerimiento_materialBCE)
    print(f"* Total de Material B requerido: {materialBCE1}")
    print("-Material C")
    requerimiento_materialCCE = float(input("Ingrese el requerimiento de material C: "))
    materialCCE1 = (unidades_a_prodCE1 * requerimiento_materialCCE)
    print(f"* Total de Material C requerido: {materialCCE1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCE2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("-Material A")
    requerimiento_materialACE2 = float(input("Ingrese el requerimiento de material A: "))
    materialACE2 = (unidades_a_prodCE2 * requerimiento_materialACE2)
    print(f"* Total de Material A requerido: {materialACE2}")
    print("-Material B")
    requerimiento_materialBCE2 = float(input("Ingrese el requerimiento de material B: "))
    materialBCE2 = (unidades_a_prodCE2 * requerimiento_materialBCE2)
    print(f"* Total de Material B requerido: {materialBCE2}")
    print("-Material C")
    requerimiento_materialCCE2 = float(input("Ingrese el requerimiento de material C: "))
    materialCCE2 = (unidades_a_prodCE2 * requerimiento_materialCCE2)
    print(f"* Total de Material C requerido: {materialCCE2}")
    print("\n")

    print("Total 2016")
    unidades_a_prodCET = int(input("Ingrese las suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material A: "))
    MaterialACET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"* Total de Material A requerido: {MaterialACET}")
    print("-Material B")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"*Total de Material B requerido: {MaterialBCET}")
    print("-Material C")
    requerimiento_materialACET = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCET = (unidades_a_prodCET * requerimiento_materialACET)
    print(f"*Total de Material C requerido: {MaterialCCET}")
    print("\n")

    print("Producto FA")
    print("Semestre 1")
    unidades_a_prodCR1 = int(input("Ingrese las unidades a producir del Semestre 1: "))
    print("-Material A")
    requerimiento_materialACR = float(input("Ingrese el requerimiento de material A: "))
    MaterialACR1 = (unidades_a_prodCR1 * requerimiento_materialACR)
    print(f"* Total de Material A requerido: {MaterialACR1}")
    print("Material B")
    requerimiento_materialBCR = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCR1 = (unidades_a_prodCR1 * requerimiento_materialBCR)
    print(f"* Total de Material B requerido: {MaterialBCR1}")
    print("Material C")
    requerimiento_materialCCR = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCR1 = (unidades_a_prodCR1 * requerimiento_materialCCR)
    print(f"* Total de Material C requerido: {MaterialCCR1}")
    print("\n")

    print("Semestre 2")
    unidades_a_prodCR2 = int(input("Ingrese las unidades a producir del Semestre 2: "))
    print("-Material A")
    requerimiento_materialACR2 = float(input("Ingrese el requerimiento de material A: "))
    MaterialACR2 = (unidades_a_prodCR2 * requerimiento_materialACR2)
    print(f"* Total de Material A requerido: {MaterialACR2}")
    print("-Material B")
    requerimiento_materialBCR2 = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCR2 = (unidades_a_prodCR2 * requerimiento_materialBCR2)
    print(f"* Total de Material B requerido: {MaterialBCR2}")
    print("-Material C")
    requerimiento_materialCCR2 = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCR2 = (unidades_a_prodCR2 * requerimiento_materialCCR2)
    print(f"* Total de Material C requerido: {MaterialCCR2}")
    print("\n")

    print("Total 2018")
    unidades_a_prodCRT = int(input("> Suma de unidades a producir de los Semestres 1 y 2: "))
    print("-Material A")
    requerimiento_materialACRT = float(input("Ingrese el requerimiento de material A: "))
    MaterialACRT = (unidades_a_prodCRT * requerimiento_materialACRT)
    print(f"* Total de Material A requerido: {MaterialACRT}")
    print("-Material B")
    requerimiento_materialBCRT = float(input("Ingrese el requerimiento de material B: "))
    MaterialBCRT = (unidades_a_prodCRT * requerimiento_materialBCRT)
    print(f"* Total de Material B requerido {MaterialBCRT}")
    print("-Material C")
    requerimiento_materialCCRT = float(input("Ingrese el requerimiento de material C: "))
    MaterialCCRT = (unidades_a_prodCRT * requerimiento_materialCCRT)
    print(f"Total de Material C requerido {MaterialCCRT}")
    print("Total de Requerimientos en gramos")
    print(f"Semestre 1 material A = {materialACL1 + materialACE1 + MaterialACR1}")
    print(f"Semestre 1 material B = {materialBCL1 + materialBCE1 + MaterialBCR1}")
    print(f"Semestre 1 material C = {materialCCL1 + materialCCE1 + MaterialCCR1}")
    print("\n")
    print(f"Semestre 2 material A = {materialACL2 + materialACE2 + MaterialACR2}")
    print(f"Semestre 2 material B = {materialBCL2 + materialBCE2 + MaterialBCR2}")
    print(f"Semestre 2 material C = {materialCCL2 + materialCCE2 + MaterialCCR2}")
    print("\n")
    print(f"Total material A = {materialACLT + MaterialACET + MaterialACRT}")
    print(f"Total material B = {materialBCLT + MaterialBCET + MaterialBCRT}")
    print(f"Total material C = {materialCCLT + MaterialCCET + MaterialCCRT}")
    print("\n")
    
def Numero5():
    print("Presupuesto de compras de materiales")
    print("Material A")
    print("Semestre 1")
    requerimiento5_matA1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matA1 = int(input("Ingrese el inventario final: "))
    total5_matA1 = (requerimiento5_matA1 + inventariofinal_matA1)
    print(f"Total de materiales: {total5_matA1}")
    print(f"Inventario inicial: {inventariofinal_matA1}")
    mat_acomprarA1 = (total5_matA1 - inventariofinal_matA1)
    print(f"Material a comprar: {mat_acomprarA1}")
    precio_compraMatA1 = int(input("Ingrese el precio material: "))
    totalcompraMatA1 = (mat_acomprarA1 * precio_compraMatA1)
    print(f"Total de material a pesos Semestre 1: $ {totalcompraMatA1}")
    print("\n")

    print("Semestre 2")
    requerimiento5_matA2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matA2 = int(input("Ingrese el inventario final: "))
    total5_matA2 = (requerimiento5_matA2 + inventariofinal_matA2)
    print(f"Total de materiales: {total5_matA2}")
    print(f"Inventario Inicial: {inventariofinal_matA1}")
    mat_acomprarA2 = (total5_matA2 - inventariofinal_matA1)
    print(f"El material a comprar es: {mat_acomprarA2}")
    precio_compaMatA2 = int(input("Ingrese el precio material: "))
    totalcompraMatA2 = (mat_acomprarA2 * precio_compaMatA2)
    print(f"Total de material a pesos en Semestre 2: $ {totalcompraMatA2}")
    print("\n")

    print("Total 2018")
    requerimiento5_matAT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matAT = int(input("Ingrese el inventario final: "))
    total5_matAT = (requerimiento5_matAT + inventariofinal_matAT)
    print(f"Total de materiales: {total5_matAT}")
    print(f"Inventario Inicial: {inventariofinal_matA1}")
    mat_acomprarAT = (total5_matAT - inventariofinal_matA1)
    print(f"El material a comprar es: {mat_acomprarAT}")
    totalcompraMatAT = (totalcompraMatA1 + totalcompraMatA2)
    print(f"Total de Material total: $ {totalcompraMatAT}")
    print("\n")

    print("Material B")
    print("Semestre 1")
    requerimiento5_matB1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matB1 = int(input("Ingrese el inventario final: "))
    total5_matB1 = (requerimiento5_matB1 + inventariofinal_matB1)
    print(f"Total de materiales: {total5_matB1}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarB1 = (total5_matB1 - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarB1}")
    precio_compaMatB1 = int(input("Ingrese el precio de material: "))
    totalcompraMatB1 = (mat_acomprarB1 * precio_compaMatB1)
    print(f"Total de Material A a pesos Semestre 1: $ {totalcompraMatB1}")
    print("\n")

    print("Semestre 2")
    requerimiento5_matB2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matB2 = int(input("Ingrese el inventario final: "))
    total5_matB2 = (requerimiento5_matB2 + inventariofinal_matB2)
    print(f"Total de materiales: {total5_matB2}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarB2 = (total5_matB2 - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarB2}")
    precio_compaMatB2 = int(input("Ingrese el precio de material: "))
    totalcompraMatB2 = (mat_acomprarB2 * precio_compaMatB2)
    print(f"Total de Material A a pesos Semestre 2: $ {totalcompraMatB2}")
    print("\n")

    print("Total 2018")
    requerimiento5_matBT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matBT = int(input("Ingrese el inventario final: "))
    total5_matBT = (requerimiento5_matBT + inventariofinal_matBT)
    print(f"Total de materiales: {total5_matBT}")
    print(f"Inventario inicial: {inventariofinal_matB1}")
    mat_acomprarBT = (total5_matBT - inventariofinal_matB1)
    print(f"El material a comprar es: {mat_acomprarBT}")
    totalcompraMatBT = (totalcompraMatB1 + totalcompraMatB2)
    print(f"Total de Material Total: $ {totalcompraMatBT}")
    print("\n")

    print("Material C")
    print("Semestre 1")
    requerimiento5_matC1 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matC1 = int(input("Ingrese el inventario final: "))
    total5_matC1 = (requerimiento5_matC1 + inventariofinal_matC1)
    print(f"Total de materiales: {total5_matC1}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarC1 = (total5_matC1 - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarC1}")
    precio_compaMatC1 = int(input("Ingrese el precio de material: "))
    totalcompraMatC1 = (mat_acomprarC1 * precio_compaMatC1)
    print(f"Total de Material C a pesos Semestre 1: $ {totalcompraMatC1}")
    print("\n")

    print("Semestre 2")
    requerimiento5_matC2 = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matC2 = int(input("Ingrese el inventario final: "))
    total5_matC2 = (requerimiento5_matC2 + inventariofinal_matC2)
    print(f"Total de materiales: {total5_matC2}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarC2 = (total5_matC2 - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarC2}")
    precio_compaMatC2 = int(input("Ingrese el precio de material: "))
    totalcompraMatC2 = (mat_acomprarC2 * precio_compaMatC2)
    print(f"Total de Material C a pesos Semestre 2: $ {totalcompraMatC2}")
    print("\n")

    print("Total 2018")
    requerimiento5_matCT = int(input("Ingrese el requerimiento de materiales: "))
    inventariofinal_matCT = int(input("Ingrese el inventario final: "))
    total5_matCT = (requerimiento5_matCT + inventariofinal_matCT)
    print(f"Total de materiales: {total5_matCT}")
    print(f"Inventario inicial: {inventariofinal_matC1}")
    mat_acomprarCT = (total5_matCT - inventariofinal_matC1)
    print(f"El material a comprar es: {mat_acomprarCT}")
    totalcompraMatCT = (totalcompraMatC1 + totalcompraMatC2)
    print(f"Total de Material: $ {totalcompraMatCT}")
    print("\n")
    comprastotalesS1 = (totalcompraMatA1 + totalcompraMatB1 + totalcompraMatC1)
    comprastotalesS2 = (totalcompraMatA2 + totalcompraMatB2 + totalcompraMatC2)
    comprastotalesT = (totalcompraMatAT + totalcompraMatBT + totalcompraMatCT)
    print(f"Compras totales Semestre 1: {comprastotalesS1}")
    print(f"Compras totales Semestre 2: {comprastotalesS2}")
    print(f"Total de Compras (Semestre 1 y 2): {comprastotalesT}")
    print("\n")


def Numero6():
    print("***Presupuesto determinacion de saldo proveedores y flijo de salida")
    saldo_proveedores2015 = int(input("Ingrese el saldo de Proveedores del 31 de diciembre 2015: "))
    compras_2016 = int(input("Ingrese las compras del 2016: "))
    total_proveedores2016 = (saldo_proveedores2015 + compras_2016)
    print(f"El Total de Proveedores 2016: {total_proveedores2016}")
    print(f"Pago proveedores 2015: {saldo_proveedores2015}")
    cobranzaproveedores_2016 = (compras_2016 * 0.5)
    print(f"Pago proveedores 2016: {cobranzaproveedores_2016}")
    salidasproveedores_2016 = (cobranzaproveedores_2016 + saldo_proveedores2015)
    print(f"Total pago 2016: {salidasproveedores_2016}")
    print(f"Saldo proveedores 2016: {total_proveedores2016 - salidasproveedores_2016}")

    
def Numero7():
    print("***Presupuesto de MO***")
    print("Producto A")
    print("Semestre 1")
    udsaProd1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsUd1 = float(input("Ingrese las horas  por unidad del Semestre 1: "))
    ttlhr1 = (udsaProd1 * hrsUd1)
    print(f"Total de horas del Semestre 1: {ttlhr1}")
    cuoph1 = float(input("Ingrese precio por hora del Semestre 1: "))
    impMOD = (ttlhr1 * cuoph1)
    print(f"Costo de MOD  del Semestre 1: {impMOD}")
    print("\n")

    print("Semestre 2")
    udsaProd2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsUd2 = float(input("Ingrese las horas por unidad del Semestre 2: "))
    ttlhr2 = (udsaProd2 * hrsUd2)
    print(f"Total de horas del Semestre 2: {ttlhr2}")
    cuoph2 = float(input("Ingrese precio por hora del Semestre 2: "))
    impMOD2 = (ttlhr2 * cuoph2)
    print(f"Costo de MOD del Semestre 2: {impMOD2}")
    print("\n")

    print("Total año 2009")
    udsaProdT = (udsaProd1 + udsaProd2)
    hr_p_ut = (hrsUd1)
    ttlhrt = (udsaProdT * hr_p_ut)
    impMODT = (impMOD + impMOD2)
    print(f"Total de horas requeridas del año: {ttlhrt}")
    print(f"Importe de MOD del año: {impMODT}")
    print("\n")

    print("Producto BI")
    print("Semestre 1")
    udsaProdCE1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsCE1 = float(input("Ingrese las horas por unidad del Semestre 1: "))
    ttlhr1c = (udsaProdCE1 * hrsCE1)
    print(f"Total de horas  del Semestre 1: {ttlhr1c}")
    cuoph1c = float(input("Ingrese precio por hora del Semestre 1: "))
    imdm1c = (ttlhr1c * cuoph1c)
    print(f"Costo de MOD del Semestre 1: {imdm1c}")
    print("\n")

    print("Semestre 2")
    udsaProdCE2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsCE2 = float(input("Ingrese las horas por unidad del Semestre 2: "))
    ttlhr2c = (udsaProdCE2 * hrsCE2)
    print(f"Total de horas  del Semestre 2: {ttlhr2c}")
    cuoph2c = float(input("Ingrese precio por hora del Semestre 2: "))
    imdm2c = (ttlhr2c * cuoph2c)
    print(f"Costo de MOD del Semestre 2: {imdm2c}")
    print("\n")

    print("Total Año 2009")
    un_a_ptc = (udsaProdCE1 + udsaProdCE2)
    hr_p_utc = (hrsCE1)
    ttlhrtc = (un_a_ptc * hr_p_utc)
    imdmtc = (imdm1c + imdm2c)
    print(f"Total de horas requeridas del año es: {ttlhrtc}")
    print(f"Importe de MOD del año es: {imdmtc}")
    print("\n")

    print("Producto FA")
    print("Semestre 1")
    udsaProdCR1 = float(input("Ingrese las unidades a producir del Semestre 1: "))
    hrsCR1 = float(input("Ingrese las horas por unidad del Semestre 1: "))
    ttlhr1d = (udsaProdCR1 * hrsCR1)
    print(f"Total de horas del Semestre 1 es: {ttlhr1d}")
    cuoph1d = float(input("Ingrese precio por hora del Semestre 1: "))
    imdm1d = (ttlhr1d * cuoph1d)
    print(f"Costo de MOD del Semestre 1: {imdm1d}")
    print("\n")

    print("Semestre 2")
    udsaProdCR2 = float(input("Ingrese las unidades a producir del Semestre 2: "))
    hrsCR2 = float(input("Ingrese las horas por unidad del Semestre 2: "))
    ttlhr2d = (udsaProdCR2 * hrsCR2)
    print(f"Total de horas del Semestre 2: {ttlhr2d}")
    cuoph2d = float(input("Ingrese precio por hora del Semestre 2: "))
    imdm2d = (ttlhr2d * cuoph2d)
    print(f"Costo de MOD del Semestre 2: {imdm2d}")
    print("\n")

    print("Total Año 2009")
    un_a_ptd = (udsaProdCR1 + udsaProdCR2)
    hr_p_utd = (hrsCR1)
    ttlhrtd = (un_a_ptd * hr_p_utd)
    imdmtd = (imdm1d + imdm2d)
    print(f"Total de horas requeridas del año: {ttlhrtd}")
    print(f"Costo de MOD del año: {imdmtd}")

    print(f"Total de horas requeridas por Semestre (1): {(ttlhr1 + ttlhr1c + ttlhr1d)}")
    print(f"Total de horas requeridas por Semestre (2): {(ttlhr2 + ttlhr2c + ttlhr2d)}")
    print(f"Total de horas requeridas por Semestre del Año: {(ttlhrt + ttlhrtc + ttlhrtd)}")

    print(f"Total de MOD por Semestre (1): {(impMOD + imdm1c + imdm1d)}")
    print(f"Total de MOD por Semestre (2): {(impMOD2 + imdm2c + imdm2d)}")
    print(f"Total de MOD por Semestre del Año: {(impMODT + imdmtc + imdmtd)}")


def Numero8():
    print("***Presupuesto de GIF***")
    print("Semestre 1")
    deprec1 = int(input("Depreciacion del Semestre 1: "))
    seguros1 = int(input("Costo de seguros del Semestre 1: "))
    mtnmto1 = int(input("Costo de Mantenimiento del Semestre 1: "))
    energeticos1 = int(input("Costo de energeticos del Semestre1: "))
    varios1 = int(input("Costos varios del Semestre 1: "))
    ttls1 = (deprec1 + seguros1 + mtnmto1 + energeticos1 + varios1)
    print(f"Total GIF. Semestre 1: {ttls1}")
    print("\n")
    print("Semestre 2")
    deprec2 = int(input("Depreciacion del Semestre 2: "))
    seguros2 = int(input("Costo de seguros del Semestre 2: "))
    mtnmto2 = int(input("Costo de mantenimiento del Semestre 2: "))
    energeticos2 = int(input("Costo de energeticos del Semestre 2: "))
    varios2 = int(input("Costos varios del Semestre 2: "))
    ttls2 = (deprec2 + seguros2 + mtnmto2 + energeticos2 + varios2)
    print("\n")
    print("Total Año")
    dept = (deprec1 + deprec2)
    segt = (seguros1 + seguros2)
    mantt = (mtnmto1 + mtnmto2)
    enert = (energeticos1 + energeticos2)
    vart = (varios1 + varios2)
    ttlst = (dept + segt + mantt + enert + vart)
    print(f"Total GIF del Semestre 2: {ttls2}")
    print(f"Total GIF del Año: {ttlst}")
    print("Coeficiente para determinar el costo por hora de gastos indirectos de fabricacion")
    print(f"Total de GIF {ttlst}")
    totalhrsanual = int(input("Ingrese el Total de horas MOD Anual: "))
    print(f"Costo por Hora de GIF {ttlst/totalhrsanual} redondeado")
    
def Numero9():
    print("***Presupuesto de gastos de operacion***")
    print("Semestre 1")
    deprec1 = int(input("Ingrese la Depreciacion del Semestre 1: "))
    sueysal1 = int(input("Ingrese los sueldos y salarios del Semestre 1: "))
    com1 = int(input("Ingrese el costo de las comisiones del Semestre 1: "))
    varios1 = int(input(" Ingrese los costos varios del Semestre 1: "))
    intpo1 = int(input("Ingrese los interes por obligaciones del Semestre 1: "))
    ttlgo1 = (deprec1 + sueysal1 + com1 + varios1 + intpo1)
    print(f"Total de Gastos de Operacion del Semestre 1: {ttlgo1}")
    print("\n")

    print("Semestre 2")
    deprec2 = int(input("Ingrese la Depreciacion del Semestre 2: "))
    sueysal2 = int(input("Ingrese los sueldos y salarios del Semestre 2: "))
    com2 = int(input("Ingrese el costo de las comisiones del Semestre 2: "))
    varios2 = int(input("Ingrese los costos varios del Semestre 2: "))
    intpo2 = int(input("Ingrese los interes por obligaciones del Semestre 2: "))
    ttlgo2 = (deprec2 + sueysal2 + com2 + varios2 + intpo2)
    print(f"Total de Gastos de Operacion del Semestre 2: {ttlgo2}")
    print("\n")

    print("Total Año")
    dept = (deprec1 + deprec2)
    sueysalt = (sueysal1 + sueysal2)
    comt = (com1 + com2)
    vart = (varios1 + varios2)
    intpot = (intpo1 + intpo2)
    ttlgot = (dept + sueysalt + comt + vart + intpot)
    print(f"Total de Gastos de Operacion del año: {ttlgot}")
    
    
def Numero10():
    print("***Presupuesto determinacion del costo unitario de productos terminados***")
    print("Producto A:")
    print("Costo")
    cosAMaterialA = 19.00
    cosAMaterialB = 5.00
    cosAMaterialC = 5.00
    cosAMDO = 16.00
    cosAGIF = 3.17
    print(f"Costo Material de Material A Producto A: {cosAMaterialA}")
    print(f"Costo Material de Material B Producto A: {cosAMaterialB}")
    print(f"Costo Material de Material C Producto A: {cosAMaterialC}")
    print(f"Costo Material de Mano de Obra Producto A: {cosAMDO}")
    print(f"Costo Material de Gasto Indirectos Producto A: {cosAGIF}")

    print("Cantidad")
    canAMaterialA = 2.00
    canAMaterialB = 0.50
    canAMaterialC = 20.00
    canAMDO = 3.00
    canAGIF = 3.00
    print(f"Cantidad Material A: {canAMaterialA}")
    print(f"Cantidad Material B: {canAMaterialB}")
    print(f"Cantidad Material C: {canAMaterialC}")
    print(f"Cantidad Mano de Obra: {canAMDO}")
    print(f"Cantidad Gastos Indirectos: {canAGIF}")

    print("Costo Unitario")
    cuAMaterialA = 12.00
    cuAMaterialB = 1.50
    cuAMaterialC = 20.00
    cuAMDO = 36.00
    print(f"Costo Unitario Material A: {cuAMaterialA}")
    print(f"Costo Unitario Material B: {cuAMaterialB}")
    print(f"Costo Unitario Material C: {cuAMaterialC}")
    print(f"Costo Unitario Mano de obra: {cuAMDO}")
    CuAGasIndeFab = float(input("Ingrese el costo unitario de la gastos indirectos de fabricacion: "))
    print (f"El resultado del costo unitario del producto A es: {(cuAMaterialA + cuAMaterialB + cuAMaterialC + cuAMDO + CuAGasIndeFab)}")
    print("\n")

    print("Producto BI")
    print("Costo")
    cosBIMaterialA = 19.00
    cosBIMaterialB = 5.00
    cosBIMaterialC = 5.00
    cosBIMDO = 16.00
    cosBIGIF = 3.17
    print(f"Costo Material de Material A Producto BI: {cosBIMaterialA}")
    print(f"Costo Material de Material B Producto BI: {cosBIMaterialB}")
    print(f"Costo Material de Material C Producto BI: {cosBIMaterialC}")
    print(f"Costo Material de Mano de Obra Producto BI: {cosBIMDO}")
    print(f"Costo Material de Gasto Indirectos Producto BI: {cosBIGIF}")

    print("Cantidad")
    CanBIMaterialA = float(input("Ingrese la cantidad del Material A: "))
    CanBIMaterialB = float(input("Ingrese la cantidad del Material B: "))
    CanBIMaterialC = float(input("Ingrese la cantidad del Material C: "))
    canBIMDO = float(input("Ingrese la cantidad de Mano de Obra: "))
    canBIGIF = float(input("Ingrese la cantidad de gastos indirectos: "))

    print("Costo unitario")
    CuBIMaterialA = float(input("Ingrese el costo unitario del Material A: "))
    CuBIMaterialB = float(input("Ingrese el costo unitario del Material B: "))
    CuBIMaterialC = float(input("Ingrese el costo unitario del Material C: "))
    cuBIMDO = float(input("Ingrese el costo unitario de la mano de obra: "))
    cuBIGIF = float (input("Ingrese el costo unitario de la gastos indirectos: "))
    print (f"El resultado del costo unitario del producto BI es: {(CuBIMaterialA + CuBIMaterialB + CuBIMaterialC + cuBIMDO + cuBIGIF)}")
    print("\n")

    print("Para el producto FA")
    print("Costo")
    cosFAMaterialA = 19.00
    cosFAMaterialB = 5.00
    cosFAMaterialC = 5.00
    cosFAMDO = 16.00
    cosFAGIF = 3.17
    print(f"Costo Material de Material A Producto FA: {cosFAMaterialA}")
    print(f"Costo Material de Material B Producto FA: {cosFAMaterialB}")
    print(f"Costo Material de Material C Producto FA: {cosFAMaterialC}")
    print(f"Costo Material de Mano de Obra Producto FA: {cosFAMDO}")
    print(f"Costo Material de Gasto Indirectos Producto FA: {cosFAGIF}")

    print("Cantidad")
    CanCRMaterialA = float(input("Ingrese la cantidad del Material A: "))
    CanCRMaterialB = float(input("Ingrese la cantidad del Material B: "))
    CanCRMaterialC = float(input("Ingrese la cantidad del Material C: "))
    CanCRManoDeObra = float(input("Ingrese la cantidad de la Mano de obra: "))
    CanCRGasIndeFab = float(input("Ingrese la cantidad de gastos indirectos: "))

    print("Costo unitario")
    CuFAMaterialA = float(input("Ingrese el costo unitario del Material A: "))
    CuFAMaterialB = float(input("Ingrese el costo unitario del Material B: "))
    CuFAMaterialC = float(input("Ingrese el costo unitario del Material C: "))
    CuFAManoDeObra = float(input("Ingrese el costo unitario de la mano de obra: "))
    CuFAGasIndeFab = float (input("Ingrese el costo unitario de la gastos indirectos: "))
    print (f"El resultado del costo unitario del producto FA es: {(CuFAMaterialA + CuFAMaterialB + CuFAMaterialC + CuFAManoDeObra + CuFAGasIndeFab)}")
    print("\n")

def Numero11():
    print ("***Valuacion de inventarios finales***")
    print("Inventario Final de Materiales")
    print(" Unidades ")
    unidadesmat_A = int(input("Ingrese Unidades de Material A: "))
    costo_u_matA = float(input("Ingrese el Costo Unitario Material A: "))
    costo_totalA = (unidadesmat_A *costo_u_matA)
    print(f"Costo total: {costo_totalA}")

    unidadesmat_B = int(input("Ingrese Unidades de Material B: "))
    costo_u_matB = float(input("Ingrese el Costo Unitario Material B: "))
    costo_totalB = (unidadesmat_B *costo_u_matB)
    print(f"Costo total: {costo_totalB}")

    unidadesmat_C = int(input("Ingrese Unidades de Material c: "))
    costo_u_matC = float(input("Ingrese el Costo Unitario Material C: "))
    costo_totalC = (unidadesmat_C *costo_u_matC)
    print(f"Costo total: {costo_totalC}")
    print(f"Inventario final de materiales: {costo_totalA + costo_totalB + costo_totalC}")

    print(" Inventario Final de Producto Terminado ")
    PA = int(input("Ingrese Unidades del Producto A: "))
    CUA = float(input("Ingrese costo unitario del Producto A"))
    costo_A = (PA * CUA)
    print(f"Costo total: {costo_A}")
    PBI = int(input("Ingrese Unidades del Producto BI: "))
    CUBI = float(input("Ingrese costo unitario del Producto BI"))
    costo_BI = (PBI * CUBI)
    print(f"Costo total: {costo_BI}")
    PFA = int(input("Ingrese Unidades del Producto FA: "))
    CUFA = float(input("Ingrese costo unitario del Producto FA"))
    costo_FA = (PFA * CUFA)
    print(f"Costo total: {costo_FA}")
    print(f"Inventario final de Producto Terminado: {costo_A + costo_BI + costo_FA}")
    
def Numero12():
    print("***Estado de Costo de Producción y Ventas*** ")
    saldo_in_mat = int(input("Dime el Saldo Inicial de Materiales: "))
    compras_mat = int(input("(+)Dime las Compras de Materiales: "))
    mat_disponible = (saldo_in_mat + compras_mat)
    print(f"(=)Materiales Disponibles: {mat_disponible}")
    inv_final = int(input("(-)Ingrese Inventario Final de Materiales: "))
    mat_uti = (mat_disponible - inv_final)
    print(f"(=)Materiales Utilizados: {mat_uti}")
    MOD = int(input("(+)Ingrese Mano de Obra Directa: "))
    GIF = int(input("(+)Ingrese Gastos de Fabricacion Indirectos: "))
    costo_prod = (mat_uti + MOD + GIF)
    print(f"(=)Costo de Produccion: {costo_prod}")
    Invet_Inicial = int(input("(+)Ingrese Inventario Inicial de Productos Terminados: "))
    tot_PDisp = (costo_prod + Invet_Inicial)
    print(f"(=)Total de Produccion Disponible: {tot_PDisp}")
    InventarioFinal_PT = int(input("(-)Ingrese Inventario Final de Productos Terminados: "))
    print(f"(=)Costo de Ventas: {tot_PDisp - InventarioFinal_PT}")

def Numero13():
    print("***Estado de resultados***")
    Ventas = int(input("Ingrese Ventas: "))
    Costo_Ventas = int(input("Ingrese Costo de Ventas: "))
    utilidad_bruta = (Ventas - Costo_Ventas)
    print(f"(=) Utilidad Bruta: {utilidad_bruta}")
    gastos_oper = int(input("Ingrese Gastos de Operacion: "))
    utilidad_oper = (utilidad_bruta - gastos_oper)
    print(f"(=) Utilidad de Operacion: {utilidad_oper}")
    ISR = int(input("Ingrese ISR: "))
    PTU = int(input("Ingrese PTU: "))
    print(f"Utilidad Neta: {utilidad_oper - ISR - PTU}")

def Numero14():
    print("***Estado de flujo de efectivo***")
    SaldoInicial = float(input("Ingrese el saldo inicial: "))
    Cobranza2016 = float(input("Ingrese la cantidad de la cobranza del año 2016: "))
    Cobranza2015 = float(input("Ingrese la cantidad de la cobranza del año 2015: "))
    print (f"Total de entradas: {(Cobranza2016 + Cobranza2015 )}")
    efec_disponible = (Cobranza2016 + Cobranza2015 + SaldoInicial)
    print(f"Efectivo Disponible: {efec_disponible}")

    Provedores2016 = float(input("Ingrese el saldo de Provedores en 2021: "))
    Provedores2015 = float(input("Ingrese el saldo de Provedores en 2015: "))
    pagoMOD = float(input("Ingrese el presupuesto de Mano de Obra Directa: "))
    pagGIF = float(input("Ingrese el presupuesto de Gastos Indirectos de Fabricacion: "))
    PagoGasOperacion = float(input("Ingrese el presupuesto de gastos de operacion: "))
    CompraActivoFijo = float(input("Ingrese la cantidad de Compra de Activo Fijo: "))
    PagoISR2015 = float(input("Ingrese el pago ISR del año 2015: "))
    total_salidas = (Provedores2016 + Provedores2015 + pagoMOD + pagGIF + PagoGasOperacion + CompraActivoFijo + PagoISR2015)
    print(f"Total de salidas: {total_salidas}")
    print(f"Flujo de Efectivo Actual: {efec_disponible - total_salidas}")

def Numero15():
    print("***Balance general***")
    print("Activos")
    print("Circulantes")
    efectivo = float(input("Ingrese el efectivo: "))
    clientes = float(input("Ingrese el valor de clientes: "))
    deu_div = float(input("Ingrese el valor de deudores diversos: "))
    funyemp = float(input("Ingrese el valor de funcionarios y empleados: "))
    invdm = float(input("Ingrese el valor de inventario de materiales: "))
    invdpt = float(input("Ingrese el valor de inventario de producto terminado: "))
    act_circulante = (efectivo + clientes + deu_div + funyemp + invdm + invdpt)
    print(f"El total de activos circulantes es: {act_circulante}")
    
    print("No Circulantes")
    terrenos = float(input("Proporcione el terreno: "))
    pye = float(input("Proporcione el valor de planta y equipo: "))
    deprec_acum = float(input("Ingrese el valor de depreciacion acumulada: "))
    act_nocirculante = (terrenos + pye + deprec_acum)
    print(f"El total de activos no circulantes es: {act_nocirculante}")
    
    total_activos = (act_circulante + act_nocirculante)
    print(f"El total de activos es: {total_activos}")
    print("\n")

    print("Pasivos corto plazo")
    proveedores = float(input("Proporciona el valor de proveedores: "))
    doc_pagar = float(input("Proporciona el valor de documentos por pagar: "))
    isr_pagar = float(input("Proporciona el valor de ISR por pagar: "))
    ptu_pagar = float(input("Proporciona valor de PTU por pagar: "))
    pas_cortoP = (proveedores + doc_pagar + isr_pagar + ptu_pagar)
    print(f"El total de pasivos corto plazo es: {pas_cortoP}")
    print("\n")

    print("Largo Plazo")
    obligaciones = float(input("Proporciona el valor de obligaciones por pagar: "))
    pas_largoP = (obligaciones)
    print(f"El total de pasivos largo plazo es: {pas_largoP}")
    print("\n")

    total_pasivos = (pas_cortoP + pas_largoP)
    print(f"El total de pasivo es: {total_pasivos}")

    print("Capital contable")
    capital_aportado = float(input("Escriba el valor de capital aportado: "))
    capital_ganado = float(input("Escriba el valor de capital ganado: "))
    utilidad_ejercicio = float(input("Escriba el valor de utilidad del ejercicio: "))
    total_capital = (capital_aportado + capital_ganado + utilidad_ejercicio)
    print(f"El total de capital contable es: {total_capital}")
    print("\n")
    pasivo_mas_capital = (total_capital + total_pasivos)
    print(f"La suma total de pasivo y capital es: {pasivo_mas_capital}")


while True:
    print("\n")
    main()
    numero = input("Ingrese el numero que desea: ")
    if numero == "1":
        print("\n")
        Numero1()
    elif numero == "2":
        print("\n")
        Numero2()
    elif numero == "3":
        print("\n")
        Numero3()
    elif numero == "4":
        print("\n")
        Numero4()
    elif numero == "5":
        print("\n")
        Numero5()
    elif numero == "6":
        print("\n")
        Numero6()
    elif numero == "7":
        print("\n")
        Numero7()
    elif numero == "8":
        print("\n")
        Numero8()
    elif numero == "9":
        print("\n")
        Numero9()
    elif numero == "10":
        print("\n")
        Numero10()
    elif numero == "11":
        print("\n")
        Numero11()
    elif numero == "12":
        print("\n")
        Numero12()
    elif numero == "13":
        print("\n")
        Numero13()
    elif numero == "14":
        print("\n")
        Numero14()
    elif numero == "15":
        print("\n")
        Numero15()
    elif numero == "16":
        print("\n")
        print("FINALIZO EL PROGRAMA")
        break
    else:
        print("NO EXISTE ESA OPCION, FAVOR DE INTENTAR DE NUEVO CON NUMEROS EXISTENTES")
    
    

    
    
    

